### ISSUE TITLE
 build_attrs() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by EINDEX** [chen2aaron/django-editormd#1]
我在使用此库时出现了这样的情况
我的运行环境是 Python 3.6.1 Django 1.11.3

```
Traceback (most recent call last):
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 216, in render
    nodelist.append(node.render_annotated(context))
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 216, in render
    return template.render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 216, in render
    nodelist.append(node.render_annotated(context))
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 216, in render
    nodelist.append(node.render_annotated(context))
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 1046, in render
    return render_value_in_context(output, context)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/template/base.py", line 1024, in render_value_in_context
    value = force_text(value)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/utils/encoding.py", line 76, in force_text
    s = six.text_type(s)
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/utils/html.py", line 385, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/forms/boundfield.py", line 41, in __str__
    return self.as_widget()
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/django/forms/boundfield.py", line 127, in as_widget
    **kwargs
  File "/Users/eindex/PycharmProjects/blog/venv/lib/python3.6/site-packages/editormd/widgets.py", line 22, in render
    final_attrs = self.build_attrs(attrs, name=name)
TypeError: build_attrs() got an unexpected keyword argument 'name'
[23/Jul/2017 12:02:50] "GET /admin/blog/post/2/change/ HTTP/1.1" 500 402396

```

我通过重载`build_attrs`方法修复了这个问题，[repo](https://github.com/EINDEX/django-editormd),
[commit](https://github.com/EINDEX/django-editormd/commit/97a8a17314f06cf21feb1832548020ffff0a8bb6).

如若可行，希望可以提一个 PR tks

**Comment by chen2aaron** [comment]
可以看看你是怎么使用的吗，我好在本地复现一下

**Comment by EINDEX** [comment]
[file](https://github.com/EINDEX/EINDEX-Blog/blob/master/blog/models.py) 
```python
class Post(models.Model):
    # ...
    body = EditorMdField()
    # ...
```

**Comment by chen2aaron** [comment]
emmm, 是Django1.11 兼容性的问题 
Django 1.11 修改了 build_attrs 的实现方式
已合并mr，并增加了兼容性 [#3](https://github.com/chen2aaron/django-editormd/pull/3)
推送了一个新版本0.2.5到pypi

**Comment by EINDEX** [comment]
wow！ 怎样找到 Django 具体修改版本的，可以告诉我方法吗

**Comment by chen2aaron** [comment]
我在本地运行了2个版本的 Django 发现只有1.11 会出现这个问题，然后看了下这2个版本的源码实现方式不同，再google 一下关键字 [Django 1.10.7 vs 1.11](https://fossies.org/diffs/Django/1.10.7_vs_1.11/django/forms/widgets.py-diff.html)

**Comment by EINDEX** [comment]
tks 受教了
